// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbTV8RXnyj1r3XocWtyy_NhOCfRNECvlk',
    appId: '1:311119662919:web:62d91c97dabc92bba60662',
    messagingSenderId: '311119662919',
    projectId: 'moments-a3157',
    authDomain: 'moments-a3157.firebaseapp.com',
    storageBucket: 'moments-a3157.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-KyY1nt0Q0bWsFY66cBrQMCBoIHCWozU',
    appId: '1:311119662919:android:666b9634345919dfa60662',
    messagingSenderId: '311119662919',
    projectId: 'moments-a3157',
    storageBucket: 'moments-a3157.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk3Q33JPmr-Wxj7d9C5BncgXacOld1lhw',
    appId: '1:311119662919:ios:5e175674a34b965fa60662',
    messagingSenderId: '311119662919',
    projectId: 'moments-a3157',
    storageBucket: 'moments-a3157.firebasestorage.app',
    iosBundleId: 'com.example.moments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk3Q33JPmr-Wxj7d9C5BncgXacOld1lhw',
    appId: '1:311119662919:ios:5e175674a34b965fa60662',
    messagingSenderId: '311119662919',
    projectId: 'moments-a3157',
    storageBucket: 'moments-a3157.firebasestorage.app',
    iosBundleId: 'com.example.moments',
  );
}
